### PR TITLE
Change new file dialog to select filename only

### PR DESCRIPTION
**Pull request by thechriswalker**
Allows simpler new file creation as  keyboard shortcut + type file name will work correctly, without having to move the cursor to the `newFile` bit.

Edit: had for force push - never edit file directly on the Github file editor! 😉

### CODE REVIEW

**Comment by thechriswalker** [comment]
Currently fails because, `vscode.d.ts` as imported from npm is not as up to date as I thought (running the Insiders build)... guess we have to hold out a little longer for this in stable.

**Comment by dkundel** [comment]
Thanks for contributing this! Definitely happy to merge this once this is in the stable release. Totally missed them adding this.

Cheers,
Dominik

**Comment by Telokis** [comment]
Would it be possible to launch Travis again? I don't really understand why it failed.

Error message:

```
src/file-controller.ts(151,7): error TS2345: Argument of type '{ prompt: string; value: string; valueSelection: number[]; }' is not assignable to parameter of type 'InputBoxOptions'.
Object literal may only specify known properties, and 'valueSelection' does not exist in type 'InputBoxOptions'.```

**Comment by thechriswalker** [comment]
This is the error I get locally. If I make the changes to the compiled JS, running on the Insiders build it works fine, but I can't compile it without manually patching the definitions.

The problem is that the `vscode.d.ts` file type definition for the `InputBoxOptions` doesn't (_yet_, i guess) contain the key `valueSelection` which we need to implement this functionality.

**Comment by Telokis** [comment]
Ok, I think I found it:

`Found minimal version that qualifies engine range: 1.0.0`
The engine version required is 1.0.0 and this option seem to have been added in `1.12.0` ?

This is the url of the commit in which it seems to have changed: https://github.com/Microsoft/vscode/commit/fda8a1beb4976ee7d8c20e3dc4ff84540a7e893a#diff-158dcbfd31a2238ddd6a89b8a4a23316

**Comment by thechriswalker** [comment]
It's my first time with a) VSCode and b) typescript. Hopefully this works (and the engine bump is acceptable).

**Comment by Telokis** [comment]
Have you tried locally?

**Comment by thechriswalker** [comment]
Yes, I tested locally, I meant I hope travis passes (it did 🤜 🤛 ). I haven't tested with the non-Insiders build of vscode though, but I guess that `engine` field is designed to ensure extensions are compatible.

**Comment by dkundel** [comment]
Thanks for the contribution @thechriswalker and looking into this @Telokis! I merged the changes and will release a new version after the weekend as I'll be on the road before.

Cheers,
Dominik

**Pull request merged**
